version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      discord:
        patterns:
          - "discord.js"
          - "@discordjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: ["25.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "actions/setup-node"
        versions: ["6.x"]
